# Generated by Django 6.0.3 on 2026-05-04 13:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial_data/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_data', models.JSONField(blank=True, null=True)),
                ('qc_dashboard_data', models.JSONField(blank=True, null=True)),
                ('income_risk_data', models.JSONField(blank=True, null=True)),
                ('dupont_data', models.JSONField(blank=True, null=True)),
                ('data_period', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialdataupload')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('result_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialdataupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('tier1_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('loss_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('efficiency_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('asset_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('loan_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('deposit_growth', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('credit_risk_score', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('liquidity_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('capital_adequacy', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roa_vs_benchmark', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('roe_vs_benchmark', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('efficiency_vs_benchmark', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('data_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialdataset')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('executive_summary', models.TextField()),
                ('trend_analysis', models.TextField()),
                ('financial_performance', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('benchmark_comparison', models.TextField()),
                ('recommendations', models.TextField()),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], max_length=20, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structured_data', models.JSONField(default=dict)),
                ('data_set', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='analytics.financialdataset')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('trend_analysis', 'Trend Analysis'), ('risk_assessment', 'Risk Assessment'), ('benchmark_comparison', 'Benchmark Comparison'), ('recommendations', 'Recommendations'), ('strengths_weaknesses', 'Strengths and Weaknesses')], max_length=30)),
                ('content', models.TextField()),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('key_points', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='analytics.financialdataset')),
            ],
            options={
                'ordering': ['insight_type', '-created_at'],
                'unique_together': {('data_set', 'insight_type')},
            },
        ),
    ]
