# Generated by Django 5.0 on 2026-06-29 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_analysis_prompt_defaults(apps, schema_editor):
    from analytics.services.prompt_settings_store import ensure_prompt_defaults

    ensure_prompt_defaults()


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_persisted_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('section_library', models.JSONField(blank=True, default=dict)),
                ('templates', models.JSONField(blank=True, default=dict)),
                ('default_length', models.CharField(default='standard', max_length=20)),
                ('default_detail_level', models.CharField(default='balanced', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Report configurations',
            },
        ),
        migrations.CreateModel(
            name='AnalysisPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('default_content', models.TextField()),
                ('recommended_sections', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_analysis_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['prompt_id'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(seed_analysis_prompt_defaults, migrations.RunPython.noop),
    ]
