# Generated by Django 5.0 on 2026-08-03 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_report_management_retention'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, default='Custom', max_length=100)),
                ('prompt_text', models.TextField()),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('version_current', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('related_sections', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('ai_settings', models.JSONField(blank=True, default=dict)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_modules', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prompt_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order_index', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PromptModuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('prompt_text', models.TextField()),
                ('change_comment', models.TextField(blank=True, default='')),
                ('ai_settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('tags_snapshot', models.JSONField(blank=True, default=list)),
                ('status_snapshot', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_module_versions_created', to=settings.AUTH_USER_MODEL)),
                ('prompt_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='analytics.promptmodule')),
            ],
            options={
                'ordering': ['-version_number', '-created_at'],
                'unique_together': {('prompt_module', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='ReportSectionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100)),
                ('section_title', models.CharField(max_length=255)),
                ('ai_model', models.CharField(blank=True, default='', max_length=100)),
                ('generation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, null=True, max_digits=5)),
                ('generation_run_id', models.CharField(blank=True, default='', max_length=64)),
                ('section_content', models.JSONField(blank=True, default=dict)),
                ('section_hash', models.CharField(blank=True, default='', max_length=128)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('regeneration_reason', models.CharField(blank=True, default='', max_length=255)),
                ('prompt_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.promptmodule')),
                ('prompt_module_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.promptmoduleversion')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_mappings', to='analytics.persistedreport')),
            ],
            options={
                'ordering': ['section_key', '-generation_timestamp'],
                'unique_together': {('report', 'section_key')},
            },
        ),
    ]
